FILENAME REFFILE 
	'/folders/myfolders/sasuser.v94/ExcelData/ACPC/NCvMCIprobvaluesn_ninsstat.xlsx';

PROC IMPORT DATAFILE=REFFILE DBMS=XLSX OUT=WORK.IMPORT;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.IMPORT;
RUN;

ODS GRAPHICS ON;

PROC LOGISTIC DATA=WORK.IMPORT PLOTS(ONLY)=ROC(ID=OBS);
	MODEL GROUP(EVENT='1')=NCvs_MCI;
	ODS SELECT ROCCURVE;
RUN;

ODS GRAPHICS OFF;
